server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: kubernetes
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - source_labels: [__meta_kubernetes_container_name]
    target_label: container
  - action: replace
    source_labels: [__meta_kubernetes_namespace]
    regex: (.+)
    replacement: $1
    target_label: namespace

  - action: replace
    source_labels: [__meta_kubernetes_pod_name]
    regex: (.+)
    replacement: $1
    target_label: pod

  - action: replace
    source_labels: [__meta_kubernetes_container_name]
    regex: (.+)
    replacement: $1
    target_label: container

  - source_labels: [__meta_kubernetes_pod_name]
    target_label: __path__
    replacement: /var/log/containers/${1}.log # Убедитесь, что путь корректен для ваших логов

- job_name: varlogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
